---
openapi: 3.0.1
info:
  title: API Pedidos
  version: v1
paths:
  "/api/v1/clientes":
    get:
      summary: Lista todos os clientes
      tags:
      - Clientes
      responses:
        '200':
          description: clientes encontrados
    post:
      summary: Cria um novo cliente
      tags:
      - Clientes
      parameters: []
      responses:
        '201':
          description: cliente criado
        '422':
          description: requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                data_nascimento:
                  type: string
                  format: date
                cpf:
                  type: string
                email:
                  type: string
                  format: email
              required:
              - nome
              - data_nascimento
              - cpf
              - email
  "/api/v1/clientes/{id}":
    get:
      summary: Recupera um cliente
      tags:
      - Clientes
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: cliente encontrado
        '404':
          description: cliente não encontrado
  "/api/v1/login":
    post:
      summary: Realiza o login
      tags:
      - Clientes
      parameters: []
      responses:
        '200':
          description: login efetuado com sucesso
        '422':
          description: credenciais inválidas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cpf:
                  type: string
                password:
                  type: string
              required:
              - cpf
              - password
  "/api/v1/categorias":
    get:
      summary: Lista todas as categorias
      tags:
      - Estoque
      responses:
        '200':
          description: categorias encontradas
  "/api/v1/categorias/{slug}":
    get:
      summary: Recupera uma categoria
      tags:
      - Estoque
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: categoria encontrada
        '404':
          description: categoria não encontrada
  "/api/v1/produtos":
    get:
      summary: Lista todos os produtos
      tags:
      - Estoque
      responses:
        '200':
          description: produtos encontrados
  "/api/v1/produtos/{slug}":
    get:
      summary: Recupera um produto
      tags:
      - Estoque
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: produto encontrado
        '404':
          description: produto não encontrado
  "/api/v1/pedidos":
    get:
      summary: Lista todos os pedidos
      tags:
      - Pedidos
      responses:
        '200':
          description: pedidos encontrados
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Pedido"
    post:
      summary: Cria um novo pedido
      tags:
      - Pedidos
      parameters: []
      responses:
        '201':
          description: pedido criado
        '422':
          description: requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Pedido"
  "/api/v1/pedidos/{id}":
    parameters:
    - name: id
      in: path
      description: ID do pedido
      required: true
      schema:
        type: string
    get:
      summary: Recupera um pedido
      tags:
      - Pedidos
      responses:
        '200':
          description: pedido encontrado
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Pedido"
        '404':
          description: pedido não encontrado
    put:
      summary: Atualiza um pedido
      tags:
      - Pedidos
      parameters: []
      responses:
        '200':
          description: pedido atualizado
        '422':
          description: requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Pedido"
  "/api/v1/pedidos/{id}/pagar":
    parameters:
    - name: id
      in: path
      description: ID do pedido
      required: true
      schema:
        type: string
    put:
      summary: Pagar um pedido
      tags:
      - Pedidos
      parameters: []
      responses:
        '200':
          description: pedido pagar com sucesso
        '422':
          description: requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
              - id
  "/api/v1/pedidos/{id}/receber":
    parameters:
    - name: id
      in: path
      description: ID do pedido
      required: true
      schema:
        type: string
    put:
      summary: Receber um pedido
      tags:
      - Pedidos
      parameters: []
      responses:
        '200':
          description: pedido receber com sucesso
        '422':
          description: requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
              - id
  "/api/v1/pedidos/{id}/preparar":
    parameters:
    - name: id
      in: path
      description: ID do pedido
      required: true
      schema:
        type: string
    put:
      summary: Preparar um pedido
      tags:
      - Pedidos
      parameters: []
      responses:
        '200':
          description: pedido preparar com sucesso
        '422':
          description: requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
              - id
  "/api/v1/pedidos/{id}/pronto":
    parameters:
    - name: id
      in: path
      description: ID do pedido
      required: true
      schema:
        type: string
    put:
      summary: Pronto um pedido
      tags:
      - Pedidos
      parameters: []
      responses:
        '200':
          description: pedido pronto com sucesso
        '422':
          description: requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
              - id
  "/api/v1/pedidos/{id}/finalizar":
    parameters:
    - name: id
      in: path
      description: ID do pedido
      required: true
      schema:
        type: string
    put:
      summary: Finalizar um pedido
      tags:
      - Pedidos
      parameters: []
      responses:
        '200':
          description: pedido finalizar com sucesso
        '422':
          description: requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
              - id
  "/api/v1/pedidos/{id}/qr-code":
    parameters:
    - name: id
      in: path
      description: ID do pedido
      required: true
      schema:
        type: string
    get:
      summary: Recupera o QR Code do pedido
      tags:
      - Pedidos
      responses:
        '200':
          description: QR Code retornado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  qr_code:
                    type: string
                required:
                - id
                - qr_code
        '404':
          description: pedido não encontrado
  "/api/v1/pedidos/prontos":
    get:
      summary: Lista pedidos prontos
      tags:
      - Pedidos
      responses:
        '200':
          description: lista de pedidos retornada
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Pedido"
  "/api/v1/pedidos/recebidos":
    get:
      summary: Lista pedidos recebidos
      tags:
      - Pedidos
      responses:
        '200':
          description: lista de pedidos retornada
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Pedido"
  "/api/v1/pedidos/em-preparacao":
    get:
      summary: Lista pedidos em preparação
      tags:
      - Pedidos
      responses:
        '200':
          description: lista de pedidos retornada
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Pedido"
  "/api/v1/pedidos/finalizados":
    get:
      summary: Lista pedidos finalizados
      tags:
      - Pedidos
      responses:
        '200':
          description: lista de pedidos retornada
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Pedido"
  "/api/v1/pedidos/pagamento-confirmado":
    get:
      summary: Lista pedidos com pagamento confirmado
      tags:
      - Pedidos
      responses:
        '200':
          description: lista de pedidos retornada
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Pedido"
  "/api/v1/pedidos/pagamento-em-aberto":
    get:
      summary: Lista pedidos com pagamento em aberto
      tags:
      - Pedidos
      responses:
        '200':
          description: lista de pedidos retornada
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Pedido"
  "/api/v1/pedidos/pagamento-recusado":
    get:
      summary: Lista pedidos com pagamento recusado
      tags:
      - Pedidos
      responses:
        '200':
          description: lista de pedidos retornada
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Pedido"
components:
  schemas:
    Pedido:
      type: object
      properties:
        id:
          type: string
        cliente:
          type:
          - object
          - 'null'
          properties:
            nome:
              type: string
            email:
              type: string
            cpf:
              type: integer
            token:
              type: string
        produtos:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              slug:
                type: string
              nome:
                type: string
              preco:
                type: integer
            required:
            - id
            - slug
            - nome
            - preco
        valor:
          type: number
        status:
          type:
          - string
          - 'null'
        observacao:
          type:
          - string
          - 'null'
        data:
          type: string
          format: date_time
        data_status:
          type: string
          format: date_time
        pagamento:
          type: string
      required:
      - id
      - produtos
      - valor
      - status
      - data
      - data_status
      - pagamento
