---
openapi: 3.0.1
info:
  title: API Pedidos
  version: v1
paths: {}
components:
  schemas:
    Pedido:
      type: object
      properties:
        id:
          type: string
        cliente:
          type:
          - object
          - 'null'
          properties:
            nome:
              type: string
            email:
              type: string
            cpf:
              type: integer
            token:
              type: string
        produtos:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              slug:
                type: string
              nome:
                type: string
              preco:
                type: integer
            required:
            - id
            - slug
            - nome
            - preco
        valor:
          type: number
        status:
          type:
          - string
          - 'null'
        observacao:
          type:
          - string
          - 'null'
        data:
          type: string
          format: date_time
        data_status:
          type: string
          format: date_time
        pagamento:
          type: string
      required:
      - id
      - produtos
      - valor
      - status
      - data
      - data_status
      - pagamento
