source "https://rubygems.org"

ruby "3.3.2"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1", ">= 3.1.11"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

gem 'csv'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem 'rspec-rails', require: false
  gem 'shoulda-matchers'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'mongoid-rspec'
  gem 'newman'
  gem 'webmock', '~> 3.18', '>= 3.18.1'  
  gem 'cucumber-rails', '~> 3.1', '>= 3.1.1', require: false
end

group :test do
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
end

gem 'mongoid'
gem 'active_model_serializers', '~> 0.10.0'
gem 'kaminari'

gem 'rswag'
gem 'rswag-api'
gem 'rswag-ui'

gem 'httparty', '~> 0.21.0'